salt: 
deployments:
  - name: xyz
    hash: zo/crMerI7c+tvRqmaK5Qw==
    command: "./scripts/deploy-xyz.sh"
    useValue: true
  - name: pqr
    hash:  yG2m3ATwLkHK4uZ7qgxXYQ==
    command: "./scripts/deploy-pqr.sh"
    useValue: false
